import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { renderStrokePatch } from '../src/raster.js';

// SHA256 of float32 ink buffers independently generated by utils.draw/OpenCV,
// via scripts/reference-parity.py. These detect origin, axis, rounding, width,
// circle-fill, and downsampling regressions without requiring Python in CI.
const references = [
  [[.2, .8, -.6, .7, .01, 1], .01, '9a09d078e7a93e6435847d7939330aac42866a1bfd9da895638782a455c9dae9'],
  [[.8, .1, .7, -.5, .15, 1], .01, 'd5cd9240db039ffd78cbeb7707c3b9eacddb81f7a25b647cc6a7eeb425443133'],
  [[.5, .5, 0, 0, .01, 1], .01, 'eed8623f4b412899e38de3065fbaeb4a1ecfdb4e71ce78d10eab8ab94eb2d690'],
  [[.046851908527603126, .27616955782089947, .7069764874557162, .06268962162186587, .8393384923560023, .003819922658583108], .1, '5972e08c8b47497e32ec21257ac2bfb572302221df377ac83dbf1d585b063517'],
];
for (const [index, [params, width, expected]] of references.entries()) {
  test(`stroke ${index} exactly matches Python/OpenCV reference`, () => {
    const patch = renderStrokePatch(params, width);
    assert.equal(createHash('sha256').update(new Uint8Array(patch.buffer)).digest('hex'), expected);
  });
}
